stages:
  - pre
  - lint

version:
  stage: pre
  image: alpine
  script:
    - mkdir -p $CI_PROJECT_DIR/build
    - echo `date +'%y%m%d_%H%M'`-${CI_COMMIT_SHORT_SHA} > $CI_PROJECT_DIR/build/version
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/version
    expire_in: 1 day
  retry: 2

lint:
  stage: lint
  image: milansuk/python-black:latest
  script:
    - black --check .
  tags:
    - app
