repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--config=./pyproject.toml]
      language_version: python{{ cookiecutter.python_version }}
-   repo: https://gitlab.com/pycqa/flake8
    rev: {{ cookiecutter.python_version }}
    hooks:
    - id: flake8
      args: ['--config=./.flake8']
